### ISSUE TITLE
A question about the Euclidean mean

### ISSUE THREAD

**Issue by kekehia123** [chamwen/MEKT#1]
In Table II of the paper, the input space dismension of MI1 is 6*200. The features are "six log-variance features of the CSP filtered trials". My question is how to compute the covariance matrix using these features? For each sample, we only have 6 such features and no time-series data, but according to the algorithm, we need to calculate the Euclidean mean with the features's covariance? Thank you in advance for your answer!

**Comment by chamwen** [comment]
Hi, the Table II in our paper shows the the dimensionalities of different input spaces, **the "input space" denotes different feature space**. For your concern, the 6*200 means the CSP features in the Euclidean space, its standard baseline in Euclidean space is the CSP+LDA, so we don't need to calculate the Euclidean mean. Only for the tangent and Riemanian space based methods, we need to calculate the Riemanian/Tangent/Euclidean mean on the raw time-series data.

**Comment by kekehia123** [comment]
I see. Thank you for your reply!
