### ISSUE TITLE
缺少函数mean_covariances

### ISSUE THREAD

**Issue by Hongli-Chang** [chamwen/MEKT#2]
你好，在运行例程时发现缺少函数mean_covariances，在centroid_align函数中被调用

**Comment by chamwen** [comment]
谢谢提醒，这个函数在计算黎曼均值时需要依赖黎曼工具包 [covariancetoolbox](https://github.com/alexandrebarachant/covariancetoolbox)，请下载并添加到你的matlab库中

**Comment by Hongli-Chang** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chamwen/MEKT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 晚上8:24
收件人:&nbsp;"chamwen/MEKT"<MEKT@noreply.github.com&gt;;
抄送:&nbsp;"Ocean of  Love"<726937117@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chamwen/MEKT] 缺少函数mean_covariances (#2)





 
谢谢提醒，这个函数在计算黎曼均值时需要依赖黎曼工具包 covariancetoolbox，请下载并添加到你的matlab库中
